server:
  port: 8001

# 高德地图API配置
amap:
  key: 824c511f0997586ea016f979fdb23087
  ip-url: https://restapi.amap.com/v3/ip

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径，支持多环境配置
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456